syntax = "proto3";

// Interface exported by the server
service FiveGCUManager {
  rpc getFiveGCUStatus(GetFiveGCUStatusMsg) returns (FiveGCUStatusDTO) {}
  rpc stopFiveGCU(StopFiveGCUMsg) returns (FiveGCUStatusDTO) {}
  rpc startFiveGCU(StartFiveGCUMsg) returns (FiveGCUStatusDTO) {}
  rpc initFiveGCU(InitFiveGCUMsg) returns (FiveGCUStatusDTO) {}
  rpc startFiveGCUMonitor(StartFiveGCUMonitorMsg) returns (FiveGCUStatusDTO) {}
  rpc stopFiveGCUMonitor(StopFiveGCUMonitorMsg) returns (FiveGCUStatusDTO) {}
}

// Message that the client sends to get the status of the 5G CU
message GetFiveGCUStatusMsg {}

//Message that the server returns when asked about the status of the 5G CU
message FiveGCUStatusDTO {
  bool cu_running = 1;
  string ip = 2;
  bool monitor_running = 3;
}

// Message that the client sends to stop the 5G CU
message StopFiveGCUMsg {}

// Message that the client sends to start the 5G CU
message StartFiveGCUMsg {}

// Message that the client sends to init the 5G CU
message InitFiveGCUMsg {
  string core_backhaul_ip = 1;
  string cu_backhaul_ip = 2;
  string cu_fronthaul_ip = 3;
}

// Message that the client sends to start the 5G CUMonitor
message StartFiveGCUMonitorMsg {
  string kafka_ip = 1;
  int32 kafka_port = 2;
  int32 time_step_len_seconds = 3;
}

// Message that the client sends to stop the 5G CUMonitor
message StopFiveGCUMonitorMsg {}