syntax = "proto3";

// Interface exported by the server
service FiveGDUManager {
  rpc getFiveGDUStatus(GetFiveGDUStatusMsg) returns (FiveGDUStatusDTO) {}
  rpc stopFiveGDU(StopFiveGDUMsg) returns (FiveGDUStatusDTO) {}
  rpc startFiveGDU(StartFiveGDUMsg) returns (FiveGDUStatusDTO) {}
}

// Message that the client sends to get the status of the 5G core
message GetFiveGDUStatusMsg {}

//Message that the server returns when asked about the status of the 5G core
message FiveGDUStatusDTO {
  bool du_running = 1;
  string ip = 2;
}

// Message that the client sends to stop the 5G core
message StopFiveGDUMsg {}

// Message that the client sends to start the 5G core
message StartFiveGDUMsg {}
