#!/bin/bash
# CSLE Vagrant VM provisioning script
# This script runs on each VM to prepare it for Ansible installation

set -e

NODE_NAME=${1:-"leader"}
NODE_IP=${2:-"192.168.56.10"}
IS_LEADER=${3:-"true"}
LEADER_IP=${4:-"192.168.56.10"}
CSLE_USER=${5:-"vagrant"}

echo "=============================================="
echo "Provisioning CSLE node: ${NODE_NAME}"
echo "Node IP: ${NODE_IP}"
echo "Is Leader: ${IS_LEADER}"
echo "Leader IP: ${LEADER_IP}"
echo "CSLE User: ${CSLE_USER}"
echo "=============================================="

# Update package lists
echo "[1/8] Updating package lists..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq

# Install essential packages
echo "[2/8] Installing essential packages..."
apt-get install -y -qq \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    python3 \
    python3-pip \
    python3-venv \
    git \
    make \
    build-essential \
    openssh-server \
    sshpass

# Install Ansible
echo "[3/8] Installing Ansible..."
apt-add-repository --yes --update ppa:ansible/ansible
apt-get install -y -qq ansible

# Configure SSH for passwordless access between nodes
echo "[4/8] Configuring SSH..."
if [ ! -f /home/${CSLE_USER}/.ssh/id_rsa ]; then
    sudo -u ${CSLE_USER} ssh-keygen -t rsa -b 4096 -N "" -f /home/${CSLE_USER}/.ssh/id_rsa
fi

# Add SSH config for easier node-to-node access
cat > /home/${CSLE_USER}/.ssh/config << 'EOF'
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
EOF
chmod 600 /home/${CSLE_USER}/.ssh/config
chown ${CSLE_USER}:${CSLE_USER} /home/${CSLE_USER}/.ssh/config

# Configure /etc/hosts for node discovery
echo "[5/8] Configuring /etc/hosts..."
if ! grep -q "csle-leader" /etc/hosts; then
    echo "${LEADER_IP} csle-leader leader" >> /etc/hosts
fi
if ! grep -q "${NODE_IP} csle-${NODE_NAME}" /etc/hosts; then
    echo "${NODE_IP} csle-${NODE_NAME} ${NODE_NAME}" >> /etc/hosts
fi

# Create CSLE directories
echo "[6/8] Creating CSLE directories..."
mkdir -p /var/log/csle
mkdir -p /tmp/csle
chown -R ${CSLE_USER}:${CSLE_USER} /var/log/csle
chown -R ${CSLE_USER}:${CSLE_USER} /tmp/csle

# Set up CSLE environment variables
echo "[7/8] Setting up environment variables..."
CSLE_HOME="/home/${CSLE_USER}/csle"

# Add to .bashrc if not already present
if ! grep -q "CSLE_HOME" /home/${CSLE_USER}/.bashrc; then
    cat >> /home/${CSLE_USER}/.bashrc << EOF

# CSLE Environment Variables
export CSLE_HOME=${CSLE_HOME}
export PATH=\$PATH:\$CSLE_HOME/bin
EOF
fi

# Also add to /etc/environment for system-wide access
if ! grep -q "CSLE_HOME" /etc/environment; then
    echo "CSLE_HOME=${CSLE_HOME}" >> /etc/environment
fi

# Generate Ansible variables for this Vagrant setup
echo "[8/8] Generating Ansible configuration..."
if [ "${IS_LEADER}" = "true" ]; then
    # Create Vagrant-specific Ansible variables
    # Overwrite the original variables.yml with Vagrant-specific settings
    mkdir -p /home/${CSLE_USER}/csle/ansible/group_vars/all
    cat > /home/${CSLE_USER}/csle/ansible/group_vars/all/variables.yml << EOF
# Vagrant-specific Ansible variables
# Auto-generated by provision.sh

user: "${CSLE_USER}"
csle_git_repo_url: "file:///home/${CSLE_USER}/csle"
leader_ip: "${LEADER_IP}"
leader_public_ip: "${LEADER_IP}"
nginx_content_name: "nginx_configuration_content.txt"
web_port: 7777
postgres_version: "15"
postgres_citus_version: "postgresql-15-citus-11.2"
postgresql_url: "https://install.citusdata.com/community/deb.sh"
anaconda_url: "https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh"
anaconda_install_script: "Anaconda3-2022.10-Linux-x86_64.sh"
conda_environment_name: "base"
python_version: "3.9"
postgres_password: "csle192105Test"
citus_port: 5432
csle_config:
  management_admin_username_default: "admin"
  management_admin_password_default: "csle192105Test"
  management_admin_first_name_default: "admin"
  management_admin_last_name_default: "admin"
  management_admin_email_default: "admin"
  management_admin_organization_default: "CSLE"
  management_guest_username_default: "guest"
  management_guest_password_default: "csle192105Test"
  management_guest_first_name_default: "guest"
  management_guest_last_name_default: "guestson"
  management_guest_email_default: "guest@csle.com"
  management_guest_organization_default: "CSLE"
  ssh_admin_username: "csle_admin"
  ssh_admin_password: "csle@admin-pw_191"
  ssh_agent_username: "agent"
  ssh_agent_password: "agent"
  grafana_username: "admin"
  grafana_password: "csle192105Test"
  pgadmin_username: "csle@csle.com"
  pgadmin_password: "csle192105Test"
  node_exporter_port: 9100
  grafana_port: 3000
  management_system_port: 7777
  cadvisor_port: 8080
  prometheus_port: 9090
  pgadmin_port: 7778
  node_exporter_pid_file: "/var/log/csle/node_exporter.pid"
  csle_mgmt_webapp_pid_file: "/var/log/csle/csle_mgmt_webapp.pid"
  node_exporter_log_file: "/var/log/csle/node_exporter.log"
  flask_log_file: "/var/log/csle/flask.log"
  cluster_manager_log_file: "/var/log/csle/cluster_manager.log"
  docker_stats_manager_log_file: "docker_stats_manager.log"
  docker_stats_manager_log_dir: "/var/log/csle/"
  docker_stats_manager_port: 50051
  docker_stats_manager_max_workers: 10
  docker_stats_manager_outfile: "/var/log/csle/statsmanager.out"
  docker_stats_manager_pidfile: "/var/log/csle/statsmanager.pid"
  prometheus_pid_file: "/var/log/csle/prometheus.pid"
  prometheus_log_file: "/var/log/csle/prometheus.log"
  prometheus_config_file: "\$CSLE_HOME/management-system/prometheus.yml"
  postgresql_log_dir: "/var/log/postgresql/"
  nginx_log_dir: "/var/log/nginx/"
  default_log_dir: "/tmp/csle/"
  metastore_ip: "${LEADER_IP}"
  metastore_user: "csle"
  metastore_password: "csle192105Test"
  metastore_database_name: "csle"
  localhost: false
  recovery_ai: false
  recovery_ai_output_dir: ""
  recovery_ai_examples_path: ""
  version: "0.8.0"
  cluster_config:
    cluster_nodes:
      - ip: "${LEADER_IP}"
        leader: true
        cpus: 6
        gpus: 0
        RAM: 16
  allow_registration: true
EOF
    chown ${CSLE_USER}:${CSLE_USER} /home/${CSLE_USER}/csle/ansible/group_vars/all/variables.yml
fi

echo "=============================================="
echo "Provisioning complete for node: ${NODE_NAME}"
echo "=============================================="
