cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 15.16.3.50
    bind_addr: 15.16.3.51
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  f1ap:
    bind_addr: 15.16.4.51
cu_up:
  f1u:
    socket:
      - bind_addr: 15.16.4.51
log:
  filename: /tmp/cu.log
  all_level: warning
pcap:
  ngap_enable: false
  ngap_filename: /tmp/cu_ngap.pcap

metrics:
  enable_json: true
  layers:
    enable_app_usage: true
    enable_ngap: true
    enable_e1ap: true
    enable_pdcp: true
    enable_rrc: true
  periodicity:
    app_usage_report_period: 1000
    cu_cp_report_period: 1000
    cu_up_report_period: 1000

remote_control:
  bind_addr: 127.0.0.1
  port: 55556
  enabled: true