# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: five_g_du_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'five_g_du_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66ive_g_du_manager.proto\"\x15\n\x13GetFiveGDUStatusMsg\"2\n\x10\x46iveGDUStatusDTO\x12\x12\n\ndu_running\x18\x01 \x01(\x08\x12\n\n\x02ip\x18\x02 \x01(\t\"\x10\n\x0eStopFiveGDUMsg\"\x11\n\x0fStartFiveGDUMsg2\xbb\x01\n\x0e\x46iveGDUManager\x12=\n\x10getFiveGDUStatus\x12\x14.GetFiveGDUStatusMsg\x1a\x11.FiveGDUStatusDTO\"\x00\x12\x33\n\x0bstopFiveGDU\x12\x0f.StopFiveGDUMsg\x1a\x11.FiveGDUStatusDTO\"\x00\x12\x35\n\x0cstartFiveGDU\x12\x10.StartFiveGDUMsg\x1a\x11.FiveGDUStatusDTO\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'five_g_du_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFIVEGDUSTATUSMSG']._serialized_start=27
  _globals['_GETFIVEGDUSTATUSMSG']._serialized_end=48
  _globals['_FIVEGDUSTATUSDTO']._serialized_start=50
  _globals['_FIVEGDUSTATUSDTO']._serialized_end=100
  _globals['_STOPFIVEGDUMSG']._serialized_start=102
  _globals['_STOPFIVEGDUMSG']._serialized_end=118
  _globals['_STARTFIVEGDUMSG']._serialized_start=120
  _globals['_STARTFIVEGDUMSG']._serialized_end=137
  _globals['_FIVEGDUMANAGER']._serialized_start=140
  _globals['_FIVEGDUMANAGER']._serialized_end=327
# @@protoc_insertion_point(module_scope)
